name = "opentv"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "opentv-db"
database_id = "bfe1eb68-1fa3-401a-9b59-8f712a437b47"